# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

tasks:
  docker:build:
    desc: Builds all the engines images
    silent: true
    cmd: 'docker buildx bake'

  docker:build:*:
    desc: Builds a specific engine image
    silent: true
    cmd: 'docker buildx bake {{ index .MATCH 0 }}'

  docker:pull:
    desc: Pulls all the engines images
    silent: true
    cmd: 'docker buildx bake --pull'

  docker:pull:*:
    desc: Pulls a specific engine image
    silent: true
    cmd: 'docker buildx bake {{ index .MATCH 0 }} --pull'
